theme: minima
title:J. Alfonso Maldonado
author: J. Alfonso Maldonado
email: JoseAlfonsoMaldonado@gmail. com or jalfonsom@hotmail.com
description: 
show_excerpts: true # set to false to remove excerpts on the homepage
